# Import packages

Packages are a set of functions/classes created by someone and which share a common goal

In [12]:
import numpy as np

Numpy is the most fondamental package for calculations in Python.

It allows you to create mathematical operations over vectors, matrices, tensors etc

You can also define your own pacakges but that's a bit too advanced for now

# Basic maths

In [13]:
np.sqrt(64)

8.0

In [16]:
print(np.round(1286.25698, 2))
print(np.round(1286.25698, 0))
print(np.round(1286.25698, -1))
print(np.round(1286.25698, -2))
print(np.floor(1286.25698))

1286.26
1286.0
1290.0
1300.0
1286.0


In [15]:
np.pi

3.141592653589793

In [17]:
np.sin(np.pi/2)

1.0

In [19]:
print(np.log10(1000))
print(np.exp(2))

3.0
7.38905609893


## Exercises

* compute $2020 - \dfrac{\sqrt{2*58^3+10^4*1.55}}{\sin{(e^4/6)}}$ and give answer rounded to integer

### Solution

In [10]:
np.round(2020 - (np.sqrt(2*58**3+1e4*1.55)) / (np.sin(np.exp(4)/6)),0)

26.0

# Vectors

In [20]:
l1 = [1,5,6,3]
x1 = np.array(l1)
x1

array([1, 5, 6, 3])

In [21]:
print(type(l1))
print(type(x1))
print(x1.shape)
print(x1.ndim)
print(x1.size)

<class 'list'>
<class 'numpy.ndarray'>
(4,)
1
4


In [22]:
x1[0:2]

array([1, 5])

In [25]:
x1[2]

6

In [26]:
x1

array([1, 5, 6, 3])

In [27]:
a = x1
a[0] = 0
print(x1)
print(a)

[0 5 6 3]
[0 5 6 3]


In [28]:
b = a.copy()
b[0] = 1

print(a)
print(b)

[0 5 6 3]
[1 5 6 3]


## Math operations

In [30]:
l1

[1, 5, 6, 3]

In [31]:
x1

array([0, 5, 6, 3])

In [29]:
# mathematical operations on vectors
l2 = [2,2,4,1]
x2 = np.array(l2)

print(x1 + x2)
print(l1 + l2)

[ 2  7 10  4]
[1, 5, 6, 3, 2, 2, 4, 1]


In [32]:
2 * x1

array([ 0, 10, 12,  6])

In [33]:
x1 * x2 

array([ 0, 10, 24,  3])

In [34]:
np.multiply(x1, x2)

array([ 0, 10, 24,  3])

In [35]:
x1 / x2

array([ 0. ,  2.5,  1.5,  3. ])

In [36]:
x1.dot(x2) #dot product

37

## Statistics

In [39]:
x = np.random.randint(0,100, size=1000)
print(x.shape)
print(x[:5])

(1000,)
[41 17 91 36 74]


In [40]:
print(np.min(x))
print(np.std(x))
print(np.mean(x))
print(np.percentile(x, q=[25,50,75]))

0
29.2404698834
49.911
[ 23.75  50.    76.  ]


In [41]:
np.average([1,2,3],weights = [1,1,3])

2.3999999999999999

## Generating vectors

In [42]:
np.arange(0, 30, 5)

array([ 0,  5, 10, 15, 20, 25])

In [45]:
np.linspace(-5, 5, 10)   

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [46]:
y = np.arange(0,210,30)
y

array([  0,  30,  60,  90, 120, 150, 180])

In [49]:
y2 = np.radians(y)
np.sin(y2).round(2)

array([ 0.  ,  0.5 ,  0.87,  1.  ,  0.87,  0.5 ,  0.  ])

## Stacking

In [53]:
np.vstack((x1,x2))

array([[0, 5, 6, 3],
       [2, 2, 4, 1]])

In [51]:
np.hstack((x1,x2))

array([0, 5, 6, 3, 2, 2, 4, 1])

## other

In [54]:
np.sort(x1)

array([0, 3, 5, 6])

In [56]:
x1

array([0, 5, 6, 3])

In [55]:
np.argmax(x1)

2

In [57]:
x1

array([0, 5, 6, 3])

In [58]:
np.where(x1 > 3) #indices

(array([1, 2]),)

In [59]:
x1[np.where(x1 > 3)]

array([5, 6])

In [60]:
np.extract(x1 < 4, x1)

array([0, 3])

## Exercises

* Generate 1000 random numbers via uniform distribution between 10 and 50 and store it in a vector
* compute the 5 following statistics numbers for that vector: mean, std, min, max,  median

* Generate 10000 normally distributed numbers with mean 0 and standard deviation 1
* select only values which are greater than 3 and store them in another vector
* count the number of elements it has and print the proportion of the initial vector it represents

(optional)
* is it close to the expected pvalue?

### Solution

In [15]:
urand = np.random.randint(10, 50, size=1000)

print(np.min(urand))
print(np.mean(urand))
print(np.median(urand))
print(np.std(urand))
print(np.max(urand))

10
28.611
29.0
11.4471690387
49


In [89]:
np.random.seed(10)
nrand = np.random.normal(loc = 0, scale = 1, size = 100000)

big = nrand[np.where(nrand> 3 )]
big = nrand[nrand > 3]

print("proportion of number > 3 =", len(big) / len(nrand) * 100, "%")

proportion of number > 3 = 0.126 %


from statistics, empirical rule is 99.7% is within +-3 std, so 0.15% should be higher than 3 in our case, which is pretty close

# matrices

## definition

In [74]:
x1

array([0, 5, 6, 3])

In [75]:
np.reshape(x1, (2,2))

array([[0, 5],
       [6, 3]])

In [76]:
m1 = np.matrix([[1,2], [3,4]])
m1

matrix([[1, 2],
        [3, 4]])

In [77]:
m1.shape

(2, 2)

In [78]:
m2 = np.matrix([[1,1], [2,3]])
m2

matrix([[1, 1],
        [2, 3]])

## Math operations

In [79]:
m1*m2

matrix([[ 5,  7],
        [11, 15]])

In [80]:
m1.T #transpose

matrix([[1, 3],
        [2, 4]])

In [81]:
m1.I #inverse

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [82]:
m1.A #adjoint

array([[1, 2],
       [3, 4]])

In [83]:
print(m1.max())
print(m1.mean())

4
2.5


In [ ]:
m1.reshape(1,4)

In [ ]:
np.zeros((2,2))             

In [ ]:
np.ones((3,3))

In [ ]:
np.eye(3)

In [ ]:
np.random.random((2,2)).round(2)

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

a[:2, 1:3]

In [ ]:
a

In [ ]:
np.sum(a, axis=0) #sum columns

In [ ]:
np.sum(a, axis=1) #sum rows

In [ ]:
np.empty_like(x1).shape

## solving equations

\begin{eqnarray}
x + y + z &=& 6 \\
2x + 5z &=& -4 \\
2x + 5y - z &=& 27 \\
\end{eqnarray}

is equivalent to

$$\begin{bmatrix}1 & 1 & 1 \\0 & 2 & 5 \\2 & 5 & -1\end{bmatrix} \begin{bmatrix}x \\y \\z \end{bmatrix} = \begin{bmatrix}6 \\-4 \\27 \end{bmatrix}$$

or

$$A.x = b$$

In [84]:
A = np.matrix([
    [1,1,1],
    [0,2,5],
    [2,5,-1]
])
b = np.array([6,-4,27])
np.linalg.solve(a=A, b=b)

array([ 5.,  3., -2.])

In [ ]:
np.linalg.det(A)

In [ ]:
np.linalg.inv(A)

## Excercises

Solve the following system of equations

\begin{eqnarray}
-x + 5y + 2z &=& 8 \\
6x - 2y + 9z &=& 0 \\
3x + 8y - z &=& 15 \\
\end{eqnarray}

and check the solution is indeed correct

### Solution

In [35]:
A = np.matrix([
    [-1,5,2],
    [6,-2,9],
    [3,8,-1]
])
b = np.array([8,0,15])
np.linalg.solve(a=A, b=b)

array([ 0.51020408,  1.68804665,  0.03498542])

# Example - fractals

In [86]:
import matplotlib.pyplot as plt
def mandelbrot( h,w, maxit=20 ):
    """Returns an image of the Mandelbrot fractal of size (h,w)."""
    y,x = np.ogrid[ -1.4:1.4:h*1j, -2:0.8:w*1j ]
    c = x+y*1j
    z = c
    divtime = maxit + np.zeros(z.shape, dtype=int)

    for i in range(maxit):
        z = z**2 + c
        diverge = z*np.conj(z) > 2**2            # who is diverging
        div_now = diverge & (divtime==maxit)  # who is diverging now
        divtime[div_now] = i                  # note when
        z[diverge] = 2                        # avoid diverging too much

    return divtime
plt.imshow(mandelbrot(800,800))